### ISSUE TITLE
GetComponentFromChild実装

### ISSUE THREAD

**Issue by kyubuns** [kyubuns/prefab_in_prefab#15]
<pre>
public T GetComponentFromChild<T>() where T : Component { return Child.GetComponent<T>(); }
</pre>

**Comment by kyubuns** [comment]
実行したときにまだChildが無かったら、警告メッセージ表示。

**Comment by kyubuns** [comment]
https://github.com/kyubuns/prefab_in_prefab/commit/209297741519a10ca465e676843c259c87a9c385

**Comment by thinca** [comment]
警告…?

**Comment by kyubuns** [comment]
bbd157b65fa70aa3914ee5f7f29f5dcb93a694ad
こっちでやりました（＾_＾）
が、そもそもスクリプトの実行順をいじれたので問題にはならなさそうです！

**Comment by thinca** [comment]
ﾅﾙﾎﾄﾞ!
