### ISSUE TITLE
もっと宣伝する

### ISSUE THREAD

**Issue by kyubuns** [kyubuns/prefab_in_prefab#18]
Qiitaに記事書く、はてダも書き直し
→何ができるのか！を最初にバーンと。
動画も撮り直し。字幕入れる。

**Comment by kyubuns** [comment]
色んな問題治ってから。

**Comment by kyubuns** [comment]
Qiita書いた。
http://qiita.com/kyubuns/items/5741e5281f4bb8de656c

**Comment by thinca** [comment]
:+1:
